/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  "/companies": {
    /** List all companies */
    get: operations["list"];
  };
  "/company/{companyId}": {
    /** Returns a single company */
    get: operations["getCompanyById"];
  };
  "/talentInterest": {
    post: operations["placeTalentInterest"];
  };
}

export interface components {
  schemas: {
    Company: {
      /** Format: int64 */
      id?: number;
      name?: string;
      found_date?: string;
      description?: string;
      headquarter?: string;
      technologies?: string;
      developer?: number;
      tm_rating?: number;
    };
    TalentInterest: {
      /** Format: int64 */
      id?: number;
      email?: string;
      name?: string;
      company?: components["schemas"]["Company"];
    };
    ApiResponse: {
      /** Format: int32 */
      code?: number;
      type?: string;
      message?: string;
    };
  };
}

export interface operations {
  /** List all companies */
  list: {
    responses: {
      /** successful operation */
      200: {
        content: {
          "application/json": components["schemas"]["Company"];
        };
      };
      /** Invalid status value */
      400: unknown;
    };
  };
  /** Returns a single company */
  getCompanyById: {
    parameters: {
      path: {
        /** ID of company to return */
        companyId: number;
      };
    };
    responses: {
      /** successful operation */
      200: {
        content: {
          "application/json": components["schemas"]["Company"];
        };
      };
      /** Invalid ID supplied */
      400: unknown;
      /** Company not found */
      404: unknown;
    };
  };
  placeTalentInterest: {
    responses: {
      /** successful operation */
      200: {
        content: {
          "application/json": components["schemas"]["ApiResponse"];
          "application/xml": components["schemas"]["ApiResponse"];
        };
      };
      /** Invalid TalentInterest */
      400: unknown;
    };
    /** order placed for TalentInterest the company */
    requestBody: {
      content: {
        "application/json": components["schemas"]["TalentInterest"];
      };
    };
  };
}

export interface external {}
